const MENU_DATA = [
  {cat:'Rice', items:[
    {n:'Vegetable fried Rice', d:'Fragrant stir-fried rice tossed with a selection of fresh mixed vegetables.', p:'Rs. 1,100.00', img:'images/menu/vegetable-fried-rice.jpg'},
    {n:'Egg Fried Rice', d:'Classic fried rice tumbled with scrambled eggs, scallions, and savory seasonings.', p:'Rs. 1,250.00', img:'images/menu/egg-fried-rice.jpg'},
    {n:'Chicken Fried Rice', d:'Savory fried rice cooked with tender pieces of chicken, vegetables, and aromatic spices', p:'Rs. 1,450.00', img:'images/menu/chicken-fried-rice.jpg'},
    {n:'Mixed Rice', d:'A hearty, loaded mixed rice dish prepared with a rich variety of proteins, including prawns, cuttlefish, beef, pork, sausage, eggs, and chicken', p:'Rs. 1,900.00', img:'images/menu/mixed-rice.jpg'},
    {n:'Seafood Fried Rice', d:'Delicious fried rice packed with a medley of fresh seafood and delicate seasonings.', p:'Rs. 1,900.00', img:'images/menu/seafood-fried-rice.jpg'},
    {n:'Chillie Garlic Rice', d:'Flavorful rice tossed with a fiery punch of chili and robust garlic', p:'Rs. 1,200.00', img:'images/menu/chillie-garlic-rice.jpg'},
    {n:'Nasi - Georang - Mix', d:'A rich, mixed Indonesian-style fried rice dish combining various proteins and signature spices', p:'Rs. 2,100.00', img:'images/menu/nasi-georang-mix.jpg'},
    {n:'Thai Chicken Fried Rice', d:'Fragrant Thai-style fried rice cooked with tender chicken, vegetables, eggs, and aromatic seasonings for a delicious savory taste', p:'Rs. 1,680.00', img:'images/menu/thai-chicken-fried-rice.jpg'},
    {n:'Special Singing Rice', d:'A rich and loaded rice dish prepared with prawns, cuttlefish, beef, pork, sausage, eggs, and chicken', p:'Rs. 3,800.00', img:'images/menu/special-singing-rice.jpg'},
    {n:'Hakka Fried Rice', d:'Indo-Chinese style Hakka fried rice featuring tossed grains, vegetables, and savory wok-tossed flavor', p:'Rs. 1,780.00', img:'images/menu/hakka-fried-rice.jpg'},
  ]},
  {cat:'Chicken', items:[
    {n:'Chicken Stew', d:'Tender chicken simmered in a savory, spiced gravy', p:'Rs. 2,550.00', img:'images/menu/chicken-stew.jpg'},
    {n:'Chicken Wings', d:'Juicy chicken wings seasoned and cooked for a great bite', p:'Rs. 1,650.00', img:'images/menu/chicken-wings.jpg'},
    {n:'Chillie chicken', d:'Tender chicken pieces stir-fried in a fiery chili sauce', p:'Rs. 2,700.00', img:'images/menu/chillie-chicken.jpg'},
    {n:'Crispy chicken', d:'Extra crunchy, deep-fried chicken bites full of flavor', p:'Rs. 2,800.00', img:'images/menu/crispy-chicken.jpg'},
    {n:'Devilled Chicken', d:'Spicy and tangy chicken tossed with bell peppers, onions, and chili sauce.', p:'Rs. 2,450.00', img:'images/menu/devilled-chicken.jpg'},
    {n:'Fried chicken', d:'Crispy golden-fried chicken pieces cooked to perfection', p:'Rs. 2,300.00', img:'images/menu/fried-chicken.jpg'},
  ]},
  {cat:'Beef', items:[
    {n:'Beef Stew', d:'Tender beef cooked in a rich, comforting, spiced gravy', p:'Rs. 2,790.00', img:'images/menu/beef-stew.jpg'},
    {n:'Devilled Beef', d:'Spicy devilled beef tossed with vibrant vegetables and rich sauces', p:'Rs. 2,950.00', img:'images/menu/devilled-beef.jpg'},
    {n:'Fried Beef', d:'Crispy-edged fried beef strips with deep savory flavors', p:'Rs. 2,750.00', img:'images/menu/fried-beef.jpg'},
    {n:'Kang Kung Beef', d:'Savory beef stir-fried alongside crisp kang kung greens', p:'Rs. 2,850.00', img:'images/menu/kang-kung-beef.jpg'},
  ]},
  {cat:'Pork', items:[
    {n:'Chillie Pork', d:'Spicy pork stir-fry packed with hot chilies and spices', p:'Rs. 2,650.00', img:'images/menu/chillie-pork.jpg'},
    {n:'Devilled Pork', d:'Pork chunks tossed in a spicy, sweet-and-sour devilled sauce with onions and peppers', p:'Rs. 2,400.00', img:'images/menu/devilled-pork.jpg'},
    {n:'Fried Pork', d:'Crispy, seasoned fried pork bites', p:'Rs. 2,300.00', img:'images/menu/fried-pork.jpg'},
    {n:'Kang Kung Garlic Pork', d:'Stir-fried pork cooked with fresh water spinach (kang kung) and aromatic garlic', p:'Rs. 2,550.00', img:'images/menu/kang-kung-garlic-pork.jpg'},
    {n:'Pork Stew', d:'Succulent pork slow-cooked in a rich, flavorful broth', p:'Rs. 2,700.00', img:'images/menu/pork-stew.jpg'},
  ]},
  {cat:'Fish', items:[
    {n:'Batter Fried Fish', d:'Fish fillets coated in a light, crispy batter and fried', p:'Rs. 1,850.00', img:'images/menu/batter-fried-fish.jpg'},
    {n:'Devilled Cuttle Fish', d:'Spicy, bold, and tangy devilled cuttlefish preparation', p:'Rs. 2,200.00', img:'images/menu/devilled-cuttle-fish.jpg'},
    {n:'Devilled Fish', d:'Fish chunks tossed in a fiery and tangy devilled sauce', p:'Rs. 1,950.00', img:'images/menu/devilled-fish.jpg'},
    {n:'Fish Stew', d:'Soft fish pieces simmered in a flavorful, spiced broth', p:'Rs. 1,900.00', img:'images/menu/fish-stew.jpg'},
    {n:'Fried Fish', d:'Freshly caught fish fried to a golden crisp', p:'Rs. 1,850.00', img:'images/menu/fried-fish.jpg'},
    {n:'Hot Butter Cuttle Fish', d:'Crispy cuttlefish tossed in a signature hot butter sauce with chili and spring onions', p:'Rs. 2,180.00', img:'images/menu/hot-butter-cuttle-fish.jpg'},
  ]},
  {cat:'Prawns', items:[
    {n:'Batter Prawns', d:'Plump prawns fried in a light, airy batter', p:'Rs. 3,100.00', img:'images/menu/batter-prawns.jpg'},
    {n:'Crispy Fried Prawns', d:'Extra crispy breaded prawns served hot', p:'Rs. 3,190.00', img:'images/menu/crispy-fried-prawns.jpg'},
    {n:'Devilled Prawns', d:'Prawns tossed in a spicy, glossy devilled sauce', p:'Rs. 3,400.00', img:'images/menu/devilled-prawns.jpg'},
    {n:'Fried Prawns', d:'Succulent prawns seasoned and fried until golden', p:'Rs. 2,250.00', img:'images/menu/fried-prawns.jpg'},
  ]},
  {cat:'Mutton', items:[
    {n:'Pepper Mutton Stew', d:'Tender mutton slow-cooked in a robust, heavily spiced black pepper gravy.', p:'Rs. 3,650.00', img:'images/menu/pepper-mutton-stew.jpg'},
  ]},
  {cat:'Noodles', items:[
    {n:'Chicken Noodles', d:'Flavorful noodles stir-fried with tender pieces of chicken and vegetables.', p:'Rs. 1,550.00', img:'images/menu/chicken-noodles.jpg'},
    {n:'Egg Noodles', d:'Classic stir-fried noodles cooked with scrambled egg and savory seasonings.', p:'Rs. 1,300.00', img:'images/menu/egg-noodles.jpg'},
    {n:'Seafood Noodles', d:'Stir-fried noodles prepared with a medley of fresh seafood and aromatic spices.', p:'Rs. 1,700.00', img:'images/menu/seafood-noodles.jpg'},
    {n:'Vegetable Noodles', d:'Stir-fried noodles tossed with a variety of fresh, crisp seasonal vegetables.', p:'Rs. 980.00', img:'images/menu/vegetable-noodles.jpg'},
    {n:'Special Singing Chef Noodles', d:'Stir-fried noodles tossed with egg, prawns, sausages, beef, and chicken for a flavorful and hearty mixed noodle dish', p:'Rs. 2,900.00', img:'images/menu/special-singing-chef-noodles.jpg'},
  ]},
  {cat:'Kotthu', items:[
    {n:'Cheese Kotthu', d:'A popular Sri Lankan street food classic made with chopped godamba roti, vegetables, eggs, spices, and heavily tossed with a generous amount of melted cheese for a rich and savory flavor', p:'Rs. 1,100.00', img:'images/menu/cheese-kotthu.jpg'},
    {n:'Chicken & Cheese Kotthu', d:'A decadent combination of chopped roti, tender spiced chicken pieces, eggs, vegetables, and a rich layer of melted cheese, offering an extra-savory and comforting meal', p:'Rs. 1,250.00', img:'images/menu/chicken-cheese-kotthu.jpg'},
    {n:'Egg Kotthu', d:'A rich and loaded rice dish prepared with prawns, cuttlefish, beef, pork, sausage, eggs, and chicken', p:'Rs. 900.00', img:'images/menu/egg-kotthu.jpg'},
  ]},
  {cat:'Pasta', items:[
    {n:'Cheese Pasta', d:'Pasta tossed in a delicious, velvety cheese-based sauce', p:'Rs. 1,900.00', img:'images/menu/cheese-pasta.jpg'},
    {n:'Chicken Pasta in white sauce', d:'Pasta served in a rich, creamy white sauce with tender chicken pieces', p:'Rs. 1,900.00', img:'images/menu/chicken-pasta-in-white-sauce.jpg'},
    {n:'Seafood Pasta in white sauce', d:'Pasta combined with assorted seafood in a smooth and savory white sauce.', p:'Rs. 1,900.00', img:'images/menu/seafood-pasta-in-white-sauce.jpg'},
  ]},
  {cat:'Omellete', items:[
    {n:'Cheese Omellette', d:'Fluffy omelet folded with gooey, melted cheese', p:'Rs. 1,590.00', img:'images/menu/cheese-omellette.jpg'},
    {n:'Chicken Omellette', d:'Hearty omelet stuffed with savory minced chicken', p:'Rs. 1,720.00', img:'images/menu/chicken-omellette.jpg'},
    {n:'Singin Chef Special Omellette', d:'A loaded specialty omelet containing Mushroom, Baby Corn, Parsley, Onion, and Coriander', p:'Rs. 2,250.00', img:'images/menu/singin-chef-special-omellette.jpg'},
    {n:'Sri Lankan Omellette', d:'Traditional local-style omelet loaded with onions, green chillies, and spices.', p:'Rs. 1,350.00', img:'images/menu/sri-lankan-omellette.jpg'},
  ]},
  {cat:'Specials', items:[
    {n:'Singin Chef Special Seafood Platter', d:'An ultimate seafood assortment featuring Cuttle fish, Prawns, Fish, Crab, and Fried Egg', p:'Rs. 5,800.00', img:'images/menu/singin-chef-special-seafood-platter.jpg'},
  ]},
  {cat:'Vegetables', items:[
    {n:'French Fries', d:'Classic, crispy golden french fries', p:'Rs. 1,650.00', img:'images/menu/french-fries.jpg'},
    {n:'Fried Potato wedges', d:'Thick-cut potato wedges fried to a golden crunch', p:'Rs. 1,450.00', img:'images/menu/fried-potato-wedges.jpg'},
    {n:'Mixed Boiled vegetables', d:'A healthy selection of lightly boiled, fresh seasonal vegetables', p:'Rs. 1,850.00', img:'images/menu/mixed-boiled-vegetables.jpg'},
  ]},
  {cat:'Party Bites (Per Kilo)', items:[
    {n:'Beef', d:'Beef priced per kilo', p:'Rs. 4,800.00', img:'images/menu/beef.jpg'},
    {n:'Boiled Vegetables', d:'Healthy boiled vegetables priced per kilo', p:'Rs. 2,850.00', img:'images/menu/boiled-vegetables.jpg'},
    {n:'Chicken', d:'Fresh chicken available per kilo for party bites', p:'Rs. 3,850.00', img:'images/menu/chicken.jpg'},
    {n:'Cuttle Fish', d:'Cuttlefish offered per kilo', p:'Rs. 5,500.00', img:'images/menu/cuttle-fish.jpg'},
    {n:'Fish', d:'Fresh fish priced per kilo', p:'Rs. 4,250.00', img:'images/menu/fish.jpg'},
    {n:'French Frice', d:'Crispy French fries available per kilo', p:'Rs. 3,400.00', img:'images/menu/french-frice.jpg'},
    {n:'Pork', d:'Pork available per kilo', p:'Rs. 4,300.00', img:'images/menu/pork.jpg'},
    {n:'Prawns (medium Size)', d:'Medium-sized prawns priced per kilo', p:'Rs. 600.00', img:'images/menu/prawns-medium-size.jpg'},
  ]},
  {cat:'Wraps', items:[
    {n:'Tandoori Tempo Wrap with Crispy Chip Chorus', d:'Tandoori Chicken Wrap served with Chips', p:'Rs. 2,480.00', img:'images/menu/tandoori-tempo-wrap-with-crispy-chip-chorus.jpg'},
    {n:'Seafood orchestra rap with Creamy Coastal Notes', d:'Cuttlefish & Shrimp Salad Wrap with homemade dressing', p:'Rs. 2,780.00', img:'images/menu/seafood-orchestra-rap-with-creamy-coastal-notes.jpg'},
  ]},
  {cat:'Served with two roasted bread', items:[
    {n:'Black pork with Pol Sambol and Kiri Hodi', d:'', p:'Rs. 2,780.00', img:'images/menu/black-pork-with-pol-sambol-and-kiri-hodi.jpg'},
    {n:'Jaffna Crab Curry with Pol Sambol', d:'', p:'Rs. 2,350.00', img:'images/menu/jaffna-crab-curry-with-pol-sambol.jpg'},
    {n:'Devilled chicken, kirihodi and pol sambol', d:'', p:'Rs. 2,200.00', img:'images/menu/devilled-chicken-kirihodi-and-pol-sambol.jpg'},
    {n:'Prawn Curry and Seeni sambol', d:'', p:'Rs. 3,100.00', img:'images/menu/prawn-curry-and-seeni-sambol.jpg'},
    {n:'Vegetable Kurma and Pol Sambol', d:'', p:'Rs. 1,680.00', img:'images/menu/vegetable-kurma-and-pol-sambol.jpg'},
  ]},
  {cat:'Sausages', items:[
    {n:'Devilled Sausages', d:'Sliced sausages tossed in a savory and spicy devilled sauce', p:'Rs. 1,450.00', img:'images/menu/devilled-sausages.jpg'},
  ]},
  {cat:'Kaju', items:[
    {n:'Fried Kaju', d:'Crunchy fried cashew nuts seasoned as a savory bite', p:'Rs. 2,800.00', img:'images/menu/fried-kaju.jpg'},
  ]},
  {cat:'Mushroom', items:[
    {n:'Hot Butter Mushroom', d:'Crispy mushrooms tossed in a rich, buttery, and slightly spicy glaze', p:'Rs. 1,780.00', img:'images/menu/hot-butter-mushroom.jpg'},
  ]},
  {cat:'Fruits', items:[
    {n:'Assorted Fresh Fruit platte', d:'A refreshing selection of cut seasonal fresh fruits', p:'Rs. 2,800.00', img:'images/menu/assorted-fresh-fruit-platte.jpg'},
  ]},
  {cat:'Waffles', items:[
    {n:'Melody Mayo Chicken with Spicy Veggie Backbeat', d:'Chicken Mayonnaise with Spicy Vegetable Salad', p:'Rs. 2,150.00', img:'images/menu/melody-mayo-chicken-with-spicy-veggie-backbeat.jpg'},
    {n:'Marshmallow Mezzo Ice Cream with Chocolate Crescendo', d:'Ice Cream, Marshmallow & Chocolate Sauce', p:'Rs. 1,550.00', img:'images/menu/marshmallow-mezzo-ice-cream-with-chocolate-crescendo.jpg'},
    {n:'Strawberry Sonata Swirl with Whipped Cream', d:'Vanilla Ice Cream, strawberry topping & whipped cream', p:'Rs. 2,400.00', img:'images/menu/strawberry-sonata-swirl-with-whipped-cream.jpg'},
  ]},
  {cat:'Pan Cake', items:[
    {n:'Symphony Sausage with Forest Harmony Sauce', d:'Chicken Bockwurst with Mushroom & Onion Sauce', p:'Rs. 1,650.00', img:'images/menu/symphony-sausage-with-forest-harmony-sauce.jpg'},
    {n:'Sweet Serenade Stack with Nutty Chocolate Riffs', d:'Your Choice of Ice Cream & Pancakes with Nuts & Sweet Topping', p:'Rs. 1,650.00', img:'images/menu/sweet-serenade-stack-with-nutty-chocolate-riffs.jpg'},
    {n:'Orange Sonata Pancakes with Vanilla Ice Dream', d:'Pancake with Hot Orange Sauce & Vanilla Ice Cream', p:'Rs. 1,900.00', img:'images/menu/orange-sonata-pancakes-with-vanilla-ice-dream.jpg'},
  ]},
  {cat:'Coffee', items:[
    {n:'Cappuccino', d:'A classic espresso topped with a rich layer of foamed milk', p:'Rs. 960.00', img:'images/menu/cappuccino.jpg'},
    {n:'Latte', d:'Smooth espresso combined with steamed milk and a light layer of foam.', p:'Rs. 1,100.00', img:'images/menu/latte.jpg'},
    {n:'Moca', d:'A delightful blend of rich espresso, chocolate, and steamed milk', p:'Rs. 1,200.00', img:'images/menu/moca.jpg'},
  ]},
  {cat:'Fresh Juices', items:[
    {n:'Amberalla Groove', d:'Golden ambarella with a zesty island rhythm', p:'Rs. 680.00', img:'images/menu/amberalla-groove.jpg'},
    {n:'Blood Melon on the Dance Floor', d:'Fizzy tropical fun with a juicy kick', p:'Rs. 680.00', img:'images/menu/blood-melon-on-the-dance-floor.jpg'},
    {n:'Mango Melody', d:'Smooth and velvety, the golden chart-topper.', p:'Rs. 760.00', img:'images/menu/mango-melody.jpg'},
    {n:'Pineapple Pop', d:'Fizzy tropical fun with a juicy kick', p:'Rs. 680.00', img:'images/menu/pineapple-pop.jpg'},
    {n:'Pure Passion With nature\'s Lemon Grass', d:'A refreshing blend combining the vibrant taste of passion fruit with the natural, aromatic touch of lemongrass', p:'Rs. 780.00', img:'images/menu/pure-passion-with-nature-s-lemon-grass.jpg'},
    {n:'Starlight Serenade', d:'Refreshing star fruit symphony that shines bright', p:'Rs. 660.00', img:'images/menu/starlight-serenade.jpg'},
    {n:'Tangy Tamarind Tempo', d:'Sweet and sour harmony with a tropical twist', p:'Rs. 980.00', img:'images/menu/tangy-tamarind-tempo.jpg'},
    {n:'Wood Apple Blues', d:'This song is deep, rich, and earthy, making it a soulful island classic', p:'Rs. 780.00', img:'images/menu/wood-apple-blues.jpg'},
  ]},
  {cat:'Milk Shake', items:[
    {n:'Banana Ballad', d:'Ingredients: Banana, Vanilla Ice Cream, Milk, Honey Description: Smooth, mellow, and comforting — a sweet melody for your taste buds. A classic tune that never goes out of style.', p:'Rs. 1,000.00', img:'images/menu/banana-ballad.jpg'},
    {n:'Chocolate Crescendo', d:'Ingredients: Chocolate Ice Cream, Milk, Chocolate Syrup, Whipped Cream Description: A rich, indulgent symphony of chocolate notes. Turn up the cocoa and feel the crescendo', p:'Rs. 1,000.00', img:'images/menu/chocolate-crescendo.jpg'},
    {n:'Moca Melody', d:'Ingredients: Coffee, Chocolate, Chocolate Ice Cream, Milk Description: A caffeinated chocolate groove — rich, smooth, and energising. A coffee-chocolate duet hitting all the right notes.', p:'Rs. 1,100.00', img:'images/menu/moca-melody.jpg'},
    {n:'Strawberry Swing', d:'Ingredients: Fresh Strawberries, Strawberry Ice Cream, Milk Description: Fruity, vibrant, and full of energy — a playful dance of flavor. A juicy jam session in every sip.', p:'Rs. 1,250.00', img:'images/menu/strawberry-swing.jpg'},
    {n:'Vanilla milk shake', d:'Creamy vanilla milkshake with a smooth, sweet flavor.', p:'Rs. 1,000.00', img:'images/menu/vanilla-milk-shake.jpg'},
  ]},
  {cat:'Energized Drinks', items:[
    {n:'Beet Beat', d:'Ingredients: Beetroot, Ginger, Lime Description: Bold, zesty, and energizing — earthy beet with a fiery ginger kick. Your daily rhythm in a glass!', p:'Rs. 1,000.00', img:'images/menu/beet-beat.jpg'},
    {n:'Carrot Crescendo', d:'Ingredients: Carrot, Orange, Lemon, Mint Description: Bright, refreshing, and uplifting — a sunny citrus symphony with a minty finish.', p:'Rs. 1,000.00', img:'images/menu/carrot-crescendo.jpg'},
  ]},
  {cat:'Soft Drinks', items:[
    {n:'Coca-Cola 400ml', d:'Chilled Coca-Cola with a refreshing, fizzy taste', p:'Rs. 300.00', img:'images/menu/coca-cola-400ml.jpg'},
    {n:'Sprite 400ml', d:'Crisp and refreshing lemon-lime flavored soft drink', p:'Rs. 300.00', img:'images/menu/sprite-400ml.jpg'},
    {n:'Fanta 400ml', d:'Fizzy orange-flavored soft drink with a fruity taste', p:'Rs. 300.00', img:'images/menu/fanta-400ml.jpg'},
    {n:'Ginger Ale', d:'Refreshing carbonated drink with a mild ginger flavor', p:'Rs. 300.00', img:'images/menu/ginger-ale.jpg'},
    {n:'Lemonade', d:'Sweet and tangy lemon-flavored refreshing drink.', p:'Rs. 250.00', img:'images/menu/lemonade.jpg'},
    {n:'EGB', d:'Refreshing ginger beer with a sweet and spicy taste', p:'Rs. 250.00', img:'images/menu/egb.jpg'},
    {n:'Soda', d:'Chilled carbonated water, light and refreshing', p:'Rs. 200.00', img:'images/menu/soda.jpg'},
    {n:'Tonic', d:'Sparkling water with a refreshing bitter-sweet taste', p:'Rs. 250.00', img:'images/menu/tonic.jpg'},
    {n:'Tonic Water 500ml', d:'500ml bottle of refreshing sparkling tonic water', p:'Rs. 350.00', img:'images/menu/tonic-water-500ml.jpg'},
    {n:'Cinnamon', d:'Refreshing cinnamon-flavored carbonated beverage', p:'Rs. 550.00', img:'images/menu/cinnamon.jpg'},
    {n:'Cinnamon Zero', d:'Zero-sugar cinnamon-flavored refreshing beverage', p:'Rs. 550.00', img:'images/menu/cinnamon-zero.jpg'},
    {n:'Water (500ml)', d:'Pure bottled drinking water, ideal for refreshment', p:'Rs. 100.00', img:'images/menu/water-500ml.jpg'},
    {n:'Gingerale', d:'', p:'Rs. 300.00', img:'images/menu/gingerale.jpg'},
  ]},
  {cat:'Soup', items:[
    {n:'Cream of Chicken Soup', d:'A rich, warm, and velvety soup featuring tender pieces of chicken simmered in a creamy, seasoned broth loaded with herbs and finely diced vegetables.', p:'Rs. 1,100.00', img:'images/menu/cream-of-chicken-soup.jpg'},
    {n:'Cream of Vegitable Soup', d:'A smooth, comforting, and wholesome soup made from a blend of fresh garden vegetables simmered and enriched with a creamy broth and delicate seasonings', p:'Rs. 980.00', img:'images/menu/cream-of-vegitable-soup.jpg'},
  ]},
];